const steps = {
  EXTRA_INFO: "EXTRA_INFO",
  HOW_KNOW_ABOUT_US: "HOW_KNOW_ABOUT_US",
  ABOUT_ME: "ABOUT_ME",
  CHECK_RAM: "CHECK_RAM",
  EXPERIENCE: "EXPERIENCE",
  EXTRA_INFO_ABOUT_EXPERIENCE: "EXTRA_INFO_ABOUT_EXPERIENCE",
  ENGLISH_LVL: "ENGLISH_LVL",
  READY_TO_WORK: "READY_TO_WORK",
  SALARY: "SALARY",
  PRIORITIES: "PRIORITIES",
  FINISH: "FINISH",
};

module.exports = { steps };
